name: Build Mod

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    uses: geode-sdk/build-geode-mod/.github/workflows/multiplatform.yml@main
    with:
      mod-id: jotabelike.pausestats